In [1]:
import pandas as pd 
import numpy as np 

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


pd.set_option('display.max_columns',None)



In [2]:
df_home=pd.read_csv('/Users/aurelientarroux/Desktop/Projet_prog/Projet_1/Data/Train_Data/train_home_team_statistics_df.csv')
df_away=pd.read_csv('/Users/aurelientarroux/Desktop/Projet_prog/Projet_1/Data/Train_Data/train_away_team_statistics_df.csv')

df_home.columns='home_'+df_home.columns
df_away.columns='away_'+df_away.columns

df_result=pd.read_csv('/Users/aurelientarroux/Desktop/Projet_prog/Projet_1/Data/Y_train_1rknArQ.csv')


In [3]:
base_match=pd.merge(df_home,df_away,left_on="home_ID",right_on='away_ID',how='inner')
base=pd.merge(base_match,df_result,left_on="home_ID",right_on='ID',how='inner')
base=base.drop(['home_ID','home_LEAGUE','home_TEAM_NAME','away_ID','away_LEAGUE','away_TEAM_NAME'],axis=1)


In [4]:
def resultat(row):
    if row['HOME_WINS']==1:
        return 'HOME'
    elif row['AWAY_WINS']==1:
        return 'AWAY'
    else:
        return 'DRAW'

base['Resultat']=base.apply(resultat, axis=1)
print(resultat(base.iloc[0]))
base=base.drop(['HOME_WINS','AWAY_WINS','DRAW'],axis=1)

base.dropna(inplace=True)

X = base.drop(['Resultat','ID'],axis=1)
y = base['Resultat']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


AWAY


In [5]:
liste=[]

for k in range(50,250):
    clf = RandomForestClassifier(n_estimators=k, random_state=42)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    liste+=[[k,accuracy]]
    print([k,accuracy])

liste.sort(key=lambda x: x[1])  


[50, 0.49364791288566245]
[51, 0.49122807017543857]
[52, 0.4906231094978826]
[53, 0.49364791288566245]
[54, 0.49183303085299457]
[55, 0.4882032667876588]
[56, 0.4924379915305505]
[57, 0.4882032667876588]
[58, 0.4906231094978826]
[59, 0.4863883847549909]
[60, 0.48941318814277074]
[61, 0.48880822746521474]
[62, 0.499697519661222]
[63, 0.5021173623714459]
[64, 0.5015124016938899]
[65, 0.5063520871143375]
[66, 0.499697519661222]
[67, 0.5015124016938899]
[68, 0.5039322444041138]
[69, 0.499697519661222]
[70, 0.49727767695099817]
[71, 0.4984875983061101]
[72, 0.49727767695099817]
[73, 0.49909255898366606]
[74, 0.49909255898366606]
[75, 0.4966727162734422]
[76, 0.5033272837265578]
[77, 0.4984875983061101]
[78, 0.499697519661222]
[79, 0.5015124016938899]
[80, 0.499697519661222]
[81, 0.5033272837265578]
[82, 0.5015124016938899]
[83, 0.5021173623714459]
[84, 0.4960677555958863]
[85, 0.49788263762855417]
[86, 0.4954627949183303]
[87, 0.49485783424077434]
[88, 0.49727767695099817]
[89, 0.4978826376

In [6]:
max_accuracy=liste[0][0]

clf = RandomForestClassifier(n_estimators=k, random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.5063520871143375
              precision    recall  f1-score   support

        AWAY       0.50      0.43      0.46       520
        DRAW       0.32      0.03      0.06       416
        HOME       0.51      0.84      0.64       717

    accuracy                           0.51      1653
   macro avg       0.44      0.43      0.39      1653
weighted avg       0.46      0.51      0.44      1653

[[225  15 280]
 [118  13 285]
 [105  13 599]]
